version: "3.8"

services:
  a1111:
    container_name: singularity-a1111
    image: ghcr.io/abetlen/stable-diffusion-webui:latest
    restart: unless-stopped
    
    # Podman-specific configurations
    security_opt:
      - label=disable
    
    # User mapping for Podman
    user: "${UID:-1000}:${GID:-1000}"
    
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/models:/app/stable-diffusion-webui/models:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/outputs:/app/stable-diffusion-webui/outputs:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/config:/app/stable-diffusion-webui/config:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/extensions:/app/stable-diffusion-webui/extensions:Z
    
    ports:
      - "7860:7860"
    
    environment:
      # A1111 server configuration
      - WEBUI_LISTEN=0.0.0.0
      - WEBUI_PORT=7860
      
      # Apple Silicon MPS optimizations
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
      - MPS_AVAILABLE=1
      - ACCELERATE_USE_MPS=1
      
      # M4-Specific optimizations
      - PYTORCH_MPS_PREFER_METAL=${PYTORCH_MPS_PREFER_METAL:-1}
      - PYTORCH_MPS_ALLOCATOR_POLICY=${PYTORCH_MPS_ALLOCATOR_POLICY:-garbage_collection}
      - A1111_M4_OPTIMIZATIONS=${A1111_M4_OPTIMIZATIONS:-1}
      - TORCH_COMPILE_MODE=${TORCH_COMPILE_MODE:-default}
      
      # Memory management
      - A1111_LOWVRAM=${A1111_LOWVRAM:-0}
      - A1111_MEDVRAM=${A1111_MEDVRAM:-0}
      - A1111_XFORMERS=${A1111_XFORMERS:-1}
      
      # Apple Silicon variant detection
      - APPLE_SILICON_VARIANT=${APPLE_SILICON_VARIANT:-auto}
      - PERFORMANCE_PROFILE=${PERFORMANCE_PROFILE:-balanced}
      
      # Container engine
      - CONTAINER_ENGINE=podman
    
    platform: linux/arm64
    
    deploy:
      resources:
        limits:
          memory: ${A1111_MEMORY_LIMIT:-16G}
          cpus: '${A1111_CPU_LIMIT:-0.75}'
        reservations:
          memory: ${A1111_MEMORY_RESERVATION:-2G}
          cpus: '${A1111_CPU_RESERVATION:-0.1}'
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/ || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    
    networks:
      - singularity_net
    
    logging:
      driver: "journald"
      options:
        tag: "a1111-m4-{{.Name}}"
    
    labels:
      - "io.containers.autoupdate=registry"
      - "com.singularity.service=a1111"
      - "com.singularity.platform=apple"
      - "com.singularity.engine=podman"
      - "com.singularity.m4_optimized=true"
      - "com.singularity.version=2.0"

networks:
  singularity_net:
    external: true