version: "3"

services:
  a1111:
    container_name: singularity-a1111
    image: ghcr.io/abetlen/stable-diffusion-webui:latest
    restart: unless-stopped
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/models:/app/stable-diffusion-webui/models
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/extensions:/app/stable-diffusion-webui/extensions
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/outputs:/app/stable-diffusion-webui/outputs
      - ${SINGULARITY_DRIVE:-~/Singularity}/a1111/configs:/app/stable-diffusion-webui/configs
    ports:
      - "7860:7860"
    environment:
      # Apple Silicon optimizations
      - CLI_ARGS=--listen --enable-insecure-extension-access --precision full --no-half --use-cpu all --skip-torch-cuda-test
    platform: linux/arm64  # Specify ARM64 platform for Apple Silicon
    # Resource limits for Apple Silicon
    deploy:
      resources:
        limits:
          cpus: '0.8' # Use up to 80% of available CPU
          memory: 30G
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true
