version: "3.8"

services:
  archon:
    container_name: singularity-archon-m4-optimized
    build:
      context: ${SINGULARITY_DRIVE:-~/Singularity}/Archon
      dockerfile: Dockerfile
    restart: unless-stopped
    
    # Podman-specific configurations
    security_opt:
      - label=disable
    
    # User mapping for Podman
    user: "${UID:-1000}:${GID:-1000}"
    
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/data:/app/data:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/config:/app/config:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/models:/app/models:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/logs:/app/logs:Z
    
    ports:
      - "8080:8080"
      - "8081:8081"  # API port
    
    environment:
      # Archon server configuration
      - ARCHON_HOST=0.0.0.0
      - ARCHON_PORT=8080
      - ARCHON_API_PORT=8081
      
      # Apple Silicon MPS optimizations
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
      - MPS_AVAILABLE=1
      - ACCELERATE_USE_MPS=1
      
      # M4-Specific optimizations
      - PYTORCH_MPS_PREFER_METAL=${PYTORCH_MPS_PREFER_METAL:-1}
      - PYTORCH_MPS_ALLOCATOR_POLICY=${PYTORCH_MPS_ALLOCATOR_POLICY:-garbage_collection}
      - ARCHON_M4_OPTIMIZATIONS=${ARCHON_M4_OPTIMIZATIONS:-1}
      - TORCH_COMPILE_MODE=${TORCH_COMPILE_MODE:-default}
      
      # Memory management
      - ARCHON_MAX_MEMORY=${ARCHON_MAX_MEMORY:-16G}
      - ARCHON_BATCH_SIZE=${ARCHON_BATCH_SIZE:-8}
      - ARCHON_CACHE_SIZE=${ARCHON_CACHE_SIZE:-2G}
      
      # Performance optimizations
      - ARCHON_WORKERS=${ARCHON_WORKERS:-4}
      - ARCHON_THREADS=${ARCHON_THREADS:-8}
      - ARCHON_ASYNC_MODE=${ARCHON_ASYNC_MODE:-true}
      
      # Apple Silicon variant detection
      - APPLE_SILICON_VARIANT=${APPLE_SILICON_VARIANT:-auto}
      - PERFORMANCE_PROFILE=${PERFORMANCE_PROFILE:-balanced}
      
      # Thermal management
      - ARCHON_THERMAL_THROTTLE=${ARCHON_THERMAL_THROTTLE:-auto}
      
      # Container engine
      - CONTAINER_ENGINE=podman
    
    platform: linux/arm64
    
    deploy:
      resources:
        limits:
          memory: ${ARCHON_MEMORY_LIMIT:-18G}
          cpus: '${ARCHON_CPU_LIMIT:-0.75}'
        reservations:
          memory: ${ARCHON_MEMORY_RESERVATION:-3G}
          cpus: '${ARCHON_CPU_RESERVATION:-0.15}'
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s
    
    networks:
      - singularity_net
    
    logging:
      driver: "journald"
      options:
        tag: "archon-m4-{{.Name}}"
    
    labels:
      - "io.containers.autoupdate=registry"
      - "com.singularity.service=archon"
      - "com.singularity.platform=apple"
      - "com.singularity.engine=podman"
      - "com.singularity.m4_optimized=true"
      - "com.singularity.version=2.0"

networks:
  singularity_net:
    driver: bridge
    name: singularity_network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

