version: "3.8"

services:
  comfyui:
    container_name: singularity-comfyui
    image: docker.io/p3rco/comfyui-apple:latest
    restart: unless-stopped
    
    # Podman-specific configurations
    security_opt:
      - label=disable
    
    # User mapping for Podman
    user: "${UID:-1000}:${GID:-1000}"
    
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/models:/app/ComfyUI/models:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/custom_nodes:/app/ComfyUI/custom_nodes:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/output:/app/ComfyUI/output:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/input:/app/ComfyUI/input:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/user:/app/ComfyUI/user:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/temp:/app/ComfyUI/temp:Z
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/config:/app/ComfyUI/config:Z
    
    ports:
      - "8188:8188"
    
    environment:
      # ComfyUI server configuration
      - COMFYUI_LISTEN=0.0.0.0
      - COMFYUI_PORT=8188
      - COMFYUI_ENABLE_CORS=true
      
      # Apple Silicon MPS optimizations
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
      - MPS_AVAILABLE=1
      - ACCELERATE_USE_MPS=1
      
      # M4-Specific optimizations
      - PYTORCH_MPS_PREFER_METAL=${PYTORCH_MPS_PREFER_METAL:-1}
      - PYTORCH_MPS_ALLOCATOR_POLICY=${PYTORCH_MPS_ALLOCATOR_POLICY:-garbage_collection}
      - COMFYUI_M4_OPTIMIZATIONS=${COMFYUI_M4_OPTIMIZATIONS:-1}
      - COMFYUI_ADVANCED_SAMPLING=${COMFYUI_ADVANCED_SAMPLING:-1}
      - COMFYUI_FAST_DECODE=${COMFYUI_FAST_DECODE:-1}
      - TORCH_COMPILE_MODE=${TORCH_COMPILE_MODE:-default}
      - PYTORCH_JIT_USE_NNC_NOT_NVFUSER=1
      
      # Dynamic memory management
      - COMFYUI_LOWVRAM=${COMFYUI_LOWVRAM:-0}
      - COMFYUI_NORMALVRAM=${COMFYUI_NORMALVRAM:-1}
      - COMFYUI_HIGHVRAM=${COMFYUI_HIGHVRAM:-0}
      - COMFYUI_NOVRAM=0
      
      # Performance optimizations
      - COMFYUI_FAST=1
      - COMFYUI_DONT_UPCAST_ATTENTION=${COMFYUI_DONT_UPCAST_ATTENTION:-0}
      - COMFYUI_USE_SPLIT_CROSS_ATTENTION=${COMFYUI_USE_SPLIT_CROSS_ATTENTION:-0}
      
      # Apple Silicon variant detection
      - APPLE_SILICON_VARIANT=${APPLE_SILICON_VARIANT:-auto}
      - PERFORMANCE_PROFILE=${PERFORMANCE_PROFILE:-balanced}
      
      # Thermal management
      - COMFYUI_THERMAL_THROTTLE=${COMFYUI_THERMAL_THROTTLE:-auto}
      - COMFYUI_POWER_EFFICIENT=${COMFYUI_POWER_EFFICIENT:-0}
      
      # Container engine
      - CONTAINER_ENGINE=podman
    
    platform: linux/arm64
    
    deploy:
      resources:
        limits:
          memory: ${COMFYUI_MEMORY_LIMIT:-16G}
          cpus: '${COMFYUI_CPU_LIMIT:-0.75}'
        reservations:
          memory: ${COMFYUI_MEMORY_RESERVATION:-2G}
          cpus: '${COMFYUI_CPU_RESERVATION:-0.1}'
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8188/system_stats || curl -f http://localhost:8188/ || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    
    networks:
      - singularity_net
    
    logging:
      driver: "journald"
      options:
        tag: "comfyui-m4-{{.Name}}"
    
    labels:
      - "io.containers.autoupdate=registry"
      - "com.singularity.service=comfyui"
      - "com.singularity.platform=apple"
      - "com.singularity.engine=podman"
      - "com.singularity.m4_optimized=true"
      - "com.singularity.version=2.0"

networks:
  singularity_net:
    external: true