version: '3'

services:
  ollama:
    container_name: singularity-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME:-./data/ollama}:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Apple Silicon specific configuration
    # Uses the host network for better performance on macOS
    network_mode: host
    # Note: network_mode: host will override the networks section,
    # but we keep it for compatibility with other platforms
    networks:
      - singularity_net

networks:
  singularity_net:
    name: singularity_net
    external: true
