version: "3"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: singularity-ollama
    restart: unless-stopped
    platform: linux/arm64
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/ollama:/root/.ollama
      - ${SINGULARITY_DRIVE:-~/Singularity}/ollama/models:/root/.ollama/models
      - ${SINGULARITY_DRIVE:-~/Singularity}/ollama/logs:/var/log/ollama
    ports:
      - "11434:11434"
    environment:
      # Basic Ollama configuration
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      
      # Apple Silicon M4 optimizations
      - OLLAMA_CPU_ONLY=0
      - OLLAMA_USE_METAL=1
      - OLLAMA_METAL_DEVICE_ID=0
      
      # Dynamic resource allocation based on M4 variant
      - OLLAMA_NUM_THREADS=${OLLAMA_NUM_THREADS:-12}
      - OLLAMA_MAX_MEMORY=${OLLAMA_MAX_MEMORY:-20G}
      - OLLAMA_CONTEXT_SIZE=${OLLAMA_CONTEXT_SIZE:-8192}
      
      # M4-specific performance optimizations
      - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
      - OLLAMA_PARALLEL_REQUESTS=${OLLAMA_PARALLEL_REQUESTS:-4}
      - OLLAMA_MAX_QUEUE=${OLLAMA_MAX_QUEUE:-512}
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-5m}
      
      # Apple Silicon memory management
      - OLLAMA_MMAP=${OLLAMA_MMAP:-1}
      - OLLAMA_NUMA=${OLLAMA_NUMA:-0}
      - OLLAMA_THREADS_BATCH=${OLLAMA_THREADS_BATCH:-8}
      
      # Model loading optimizations
      - OLLAMA_PRELOAD_MODELS=${OLLAMA_PRELOAD_MODELS:-}
      - OLLAMA_MODEL_CACHE_SIZE=${OLLAMA_MODEL_CACHE_SIZE:-4G}
      
      # Thermal and power management
      - OLLAMA_THERMAL_THROTTLE=${OLLAMA_THERMAL_THROTTLE:-85}
      - OLLAMA_POWER_EFFICIENT=${OLLAMA_POWER_EFFICIENT:-0}
      
      # Logging and monitoring
      - OLLAMA_LOG_LEVEL=${OLLAMA_LOG_LEVEL:-INFO}
      - OLLAMA_METRICS=${OLLAMA_METRICS:-1}
      
    # M4-optimized resource limits
    deploy:
      resources:
        limits:
          cpus: '${OLLAMA_CPU_LIMIT:-0.85}'
          memory: ${OLLAMA_MEMORY_LIMIT:-20G}
        reservations:
          cpus: '${OLLAMA_CPU_RESERVATION:-0.5}'
          memory: ${OLLAMA_MEMORY_RESERVATION:-8G}
    
    # Health check for M4 optimization monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    networks:
      - singularity_net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: singularity-open-webui
    restart: unless-stopped
    platform: linux/arm64
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/open-webui:/app/backend/data
      - ${SINGULARITY_DRIVE:-~/Singularity}/open-webui/uploads:/app/backend/data/uploads
      - ${SINGULARITY_DRIVE:-~/Singularity}/open-webui/cache:/app/backend/data/cache
    ports:
      - "3000:8080"
    environment:
      # Ollama integration
      - OLLAMA_BASE_URL=http://singularity-ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-}
      
      # M4-specific WebUI optimizations
      - WEBUI_AUTH=${WEBUI_AUTH:-False}
      - WEBUI_NAME=${WEBUI_NAME:-Singularity AI}
      - WEBUI_URL=${WEBUI_URL:-http://localhost:3000}
      
      # Performance optimizations for Apple Silicon
      - WEBUI_WORKERS=${WEBUI_WORKERS:-4}
      - WEBUI_TIMEOUT=${WEBUI_TIMEOUT:-120}
      - WEBUI_MAX_FILE_SIZE=${WEBUI_MAX_FILE_SIZE:-100}
      
      # Apple Silicon specific features
      - ENABLE_COMMUNITY_SHARING=${ENABLE_COMMUNITY_SHARING:-False}
      - ENABLE_MESSAGE_RATING=${ENABLE_MESSAGE_RATING:-True}
      - ENABLE_MODEL_FILTER=${ENABLE_MODEL_FILTER:-True}
      
      # Caching and performance
      - WEBUI_CACHE_ENABLED=${WEBUI_CACHE_ENABLED:-True}
      - WEBUI_CACHE_SIZE=${WEBUI_CACHE_SIZE:-1G}
      
    # Resource limits for Open-WebUI on M4
    deploy:
      resources:
        limits:
          cpus: '${WEBUI_CPU_LIMIT:-0.5}'
          memory: ${WEBUI_MEMORY_LIMIT:-4G}
        reservations:
          cpus: '0.2'
          memory: 1G
    
    # Health check for WebUI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true

