version: '3'

services:
  ollama:
    container_name: singularity-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      # Jetson-specific environment variables
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Orin NX 8GB specific optimizations
      - OLLAMA_NUM_THREADS=8
    runtime: nvidia
    # Resource limits optimized for Jetson Orin NX 8GB
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '8'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - singularity_net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: singularity-open-webui
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://singularity-ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped
    networks:
      - singularity_net
    # Resource limits for WebUI on Jetson Orin NX 8GB
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

networks:
  singularity_net:
    external: true
