version: '3'

services:
  ollama:
    container_name: singularity-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # x86 CPU-only configuration
    # No GPU acceleration
    networks:
      - singularity_net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: singularity-open-webui
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://singularity-ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true
