version: '3'

services:
  tavernai:
    container_name: singularity-tavernai
    image: tavernai/tavernai:latest
    restart: unless-stopped
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/tavernai/public:/home/node/app/public
      - ${SINGULARITY_DRIVE:-~/Singularity}/tavernai/config.conf:/home/node/app/config.conf
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    # x86 CPU-only configuration
    # No GPU acceleration
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true
