version: '3'

services:
  archon:
    container_name: singularity-archon
    build:
      context: ${SINGULARITY_DRIVE:-~/Singularity}/Archon
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"  # Streamlit UI
      - "8100:8100"  # Archon Service
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/data:/app/data
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/cache:/app/cache
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/logs:/app/logs
    environment:
      - BASE_URL=${ARCHON_BASE_URL:-https://api.openai.com/v1}
      - LLM_API_KEY=${ARCHON_LLM_API_KEY:-}
      - OPENAI_API_KEY=${ARCHON_OPENAI_API_KEY:-}
      - SUPABASE_URL=${ARCHON_SUPABASE_URL:-}
      - SUPABASE_SERVICE_KEY=${ARCHON_SUPABASE_SERVICE_KEY:-}
      - REASONER_MODEL=${ARCHON_REASONER_MODEL:-}
      - PRIMARY_MODEL=${ARCHON_PRIMARY_MODEL:-}
      - EMBEDDING_MODEL=${ARCHON_EMBEDDING_MODEL:-}
      # ROCm and performance optimizations
      - ROCM_VERSION=${ROCM_VERSION:-6.2.4}
      - HIP_VISIBLE_DEVICES=${HIP_VISIBLE_DEVICES:-0}
      - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-11.0.0}
      - PYTORCH_HIP_ALLOC_CONF=expandable_segments:True
      # Archon specific optimizations
      - ARCHON_BATCH_SIZE=${ARCHON_BATCH_SIZE:-32}
      - ARCHON_MAX_WORKERS=${ARCHON_MAX_WORKERS:-4}
      - ARCHON_CACHE_SIZE=${ARCHON_CACHE_SIZE:-1000}
      - ARCHON_GPU_MEMORY_FRACTION=${ARCHON_GPU_MEMORY_FRACTION:-0.8}
      # Max 395+ optimizations
      - ARCHON_RDNA3_OPTIMIZATIONS=${ARCHON_RDNA3_OPTIMIZATIONS:-1}
      - ARCHON_FLASH_ATTENTION=${ARCHON_FLASH_ATTENTION:-1}
    # AMD ROCm device access
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    # Enhanced resource management
    deploy:
      resources:
        limits:
          cpus: '${ARCHON_CPU_LIMIT:-0.8}'
          memory: ${ARCHON_MEMORY_LIMIT:-12G}
        reservations:
          cpus: '0.25'
          memory: 2G
          devices:
            - driver: amd
              capabilities: [gpu]
              count: ${ARCHON_GPU_COUNT:-1}
    # Security and performance
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    # Health monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    networks:
      - singularity_net

  archon-mcp:
    container_name: singularity-archon-mcp
    build:
      context: ${SINGULARITY_DRIVE:-~/Singularity}/Archon/mcp
    restart: unless-stopped
    depends_on:
      archon:
        condition: service_healthy
    environment:
      # Performance optimizations
      - MCP_WORKERS=${MCP_WORKERS:-2}
      - MCP_TIMEOUT=${MCP_TIMEOUT:-30}
      - MCP_CACHE_SIZE=${MCP_CACHE_SIZE:-500}
    # Resource management
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 512M
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true

