version: '3'

services:
  comfyui:
    container_name: singularity-comfyui
    image: comfyanonymous/comfyui:latest
    restart: unless-stopped
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/models:/app/ComfyUI/models
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/custom_nodes:/app/ComfyUI/custom_nodes
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/output:/app/ComfyUI/output
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/input:/app/ComfyUI/input
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/user:/app/ComfyUI/user
      - ${SINGULARITY_DRIVE:-~/Singularity}/comfyui/temp:/app/ComfyUI/temp
    ports:
      - "8188:8188"
    environment:
      - EXTRA_ARGS=--listen --enable-cors-header --preview-method auto
      # ROCm and PyTorch optimizations
      - TORCH_COMMAND=pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2
      - ROCM_VERSION=${ROCM_VERSION:-6.2.4}
      - HIP_VISIBLE_DEVICES=${HIP_VISIBLE_DEVICES:-0}
      - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-11.0.0}
      # ComfyUI specific optimizations
      - PYTORCH_HIP_ALLOC_CONF=expandable_segments:True
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - COMFYUI_VRAM_MANAGEMENT=${COMFYUI_VRAM_MANAGEMENT:-auto}
      - COMFYUI_FORCE_FP16=${COMFYUI_FORCE_FP16:-1}
      - COMFYUI_DONT_UPCAST_ATTENTION=${COMFYUI_DONT_UPCAST_ATTENTION:-1}
      - COMFYUI_USE_SPLIT_CROSS_ATTENTION=${COMFYUI_USE_SPLIT_CROSS_ATTENTION:-1}
      # Memory management
      - COMFYUI_LOWVRAM=${COMFYUI_LOWVRAM:-0}
      - COMFYUI_NORMALVRAM=${COMFYUI_NORMALVRAM:-1}
      - COMFYUI_HIGHVRAM=${COMFYUI_HIGHVRAM:-0}
      - COMFYUI_GPU_ONLY=${COMFYUI_GPU_ONLY:-0}
      # Max 395+ specific optimizations
      - COMFYUI_RDNA3_OPTIMIZATIONS=${COMFYUI_RDNA3_OPTIMIZATIONS:-1}
      - COMFYUI_FAST_DECODE=${COMFYUI_FAST_DECODE:-1}
      - COMFYUI_ATTENTION_SPLIT=${COMFYUI_ATTENTION_SPLIT:-1}
      # Performance tuning
      - COMFYUI_PREVIEW_SIZE=${COMFYUI_PREVIEW_SIZE:-512}
      - COMFYUI_DISABLE_SMART_MEMORY=${COMFYUI_DISABLE_SMART_MEMORY:-0}
    # AMD ROCm device access
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    # Enhanced resource management
    deploy:
      resources:
        limits:
          cpus: '${COMFYUI_CPU_LIMIT:-0.8}'
          memory: ${COMFYUI_MEMORY_LIMIT:-16G}
        reservations:
          cpus: '0.25'
          memory: 4G
          devices:
            - driver: amd
              capabilities: [gpu]
              count: ${COMFYUI_GPU_COUNT:-1}
    # Security and performance
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    # Health monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/system_stats"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true

