version: '3'

services:
  sillytavern:
    container_name: singularity-sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    restart: unless-stopped
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/sillytavern/config:/home/node/app/config
      - ${SINGULARITY_DRIVE:-~/Singularity}/sillytavern/data:/home/node/app/data
      - ${SINGULARITY_DRIVE:-~/Singularity}/sillytavern/plugins:/home/node/app/plugins
      - ${SINGULARITY_DRIVE:-~/Singularity}/sillytavern/extensions:/home/node/app/public/scripts/extensions/third-party
      - ${SINGULARITY_DRIVE:-~/Singularity}/sillytavern/cache:/home/node/app/cache
    ports:
      - "8008:8000"
    environment:
      - NODE_ENV=production
      # Performance optimizations
      - NODE_OPTIONS=--max-old-space-size=${SILLYTAVERN_NODE_MEMORY:-4096}
      - UV_THREADPOOL_SIZE=${SILLYTAVERN_UV_THREADS:-8}
      # SillyTavern specific settings
      - SILLYTAVERN_ENABLE_EXTENSIONS=${SILLYTAVERN_ENABLE_EXTENSIONS:-true}
      - SILLYTAVERN_AUTO_RUN=${SILLYTAVERN_AUTO_RUN:-true}
      - SILLYTAVERN_LISTEN=${SILLYTAVERN_LISTEN:-true}
      # AMD optimizations for AI backends
      - ROCM_VERSION=${ROCM_VERSION:-6.2.4}
      - HIP_VISIBLE_DEVICES=${HIP_VISIBLE_DEVICES:-0}
    # AMD ROCm device access (for AI backend integration)
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    # Enhanced resource management
    deploy:
      resources:
        limits:
          cpus: '${SILLYTAVERN_CPU_LIMIT:-0.5}'
          memory: ${SILLYTAVERN_MEMORY_LIMIT:-6G}
        reservations:
          cpus: '0.1'
          memory: 1G
          devices:
            - driver: amd
              capabilities: [gpu]
    # Health monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true

