version: '3'

services:
  ollama:
    container_name: singularity-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME:-./data/ollama}:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      # Jetson-specific environment variables
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # AGX Orin 64GB specific optimizations
      - OLLAMA_NUM_THREADS=16
    runtime: nvidia
    # Resource limits optimized for Jetson AGX Orin 64GB
    deploy:
      resources:
        limits:
          memory: 48G
          cpus: '16'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - singularity_net

networks:
  singularity_net:
    name: singularity_net
    external: true
