version: '3'

services:
  archon:
    container_name: singularity-archon
    build:
      context: ${SINGULARITY_DRIVE:-~/Singularity}/Archon
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"  # Streamlit UI
      - "8100:8100"  # Archon Service
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/archon/data:/app/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - BASE_URL=${ARCHON_BASE_URL:-https://api.openai.com/v1}
      - LLM_API_KEY=${ARCHON_LLM_API_KEY:-}
      - OPENAI_API_KEY=${ARCHON_OPENAI_API_KEY:-}
      - SUPABASE_URL=${ARCHON_SUPABASE_URL:-}
      - SUPABASE_SERVICE_KEY=${ARCHON_SUPABASE_SERVICE_KEY:-}
      - REASONER_MODEL=${ARCHON_REASONER_MODEL:-}
      - PRIMARY_MODEL=${ARCHON_PRIMARY_MODEL:-}
      - EMBEDDING_MODEL=${ARCHON_EMBEDDING_MODEL:-}
    # Jetson-specific configuration
    runtime: nvidia
    # Resource limits optimized for Jetson Orin Nano 8GB
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '6'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - singularity_net

  archon-mcp:
    container_name: singularity-archon-mcp
    build:
      context: ${SINGULARITY_DRIVE:-~/Singularity}/Archon/mcp
    restart: unless-stopped
    depends_on:
      - archon
    # Resource limits optimized for Jetson Orin Nano 8GB
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1'
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true
