version: '3'

services:
  n8n:
    container_name: singularity-n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/n8n:/home/node/.n8n
    # Jetson-specific configuration
    runtime: nvidia
    # Resource limits optimized for Jetson Orin Nano 4GB
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '4'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true
