version: '3'

services:
  ollama:
    container_name: singularity-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME:-./data/ollama}:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      # Jetson-specific environment variables
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Orin Nano 4GB specific optimizations
      - OLLAMA_NUM_THREADS=4
    runtime: nvidia
    # Resource limits optimized for Jetson Orin Nano 4GB
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '4'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - singularity_net

networks:
  singularity_net:
    name: singularity_net
    external: true
