version: '3'

services:
  ollama:
    container_name: singularity-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME:-./data/ollama}:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    # DGX-specific configuration for multi-GPU systems
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Resource limits optimized for DGX systems
    # These can be adjusted based on specific DGX model
    shm_size: 16g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - singularity_net

networks:
  singularity_net:
    name: singularity_net
    external: true
