version: '3'

services:
  tavernai:
    container_name: singularity-tavernai
    image: tavernai/tavernai:latest
    restart: unless-stopped
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/tavernai/public:/home/node/app/public
      - ${SINGULARITY_DRIVE:-~/Singularity}/tavernai/config.conf:/home/node/app/config.conf
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # DGX-specific configuration for multi-GPU systems
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Resource limits optimized for DGX systems
    shm_size: 16g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true
