version: '3'

services:
  n8n:
    container_name: singularity-n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
    volumes:
      - ${SINGULARITY_DRIVE:-~/Singularity}/n8n:/home/node/.n8n
    # RTX-specific configuration for consumer NVIDIA GPUs
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Resource limits optimized for consumer NVIDIA GPUs
    shm_size: 8g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - singularity_net

networks:
  singularity_net:
    external: true
